#!/bin/bash
# Rathole Client Installation Script for macOS
# Run this on your Mac to set up the tunnel client

set -e

ORACLE_IP="${1}"

if [ -z "$ORACLE_IP" ]; then
    echo "❌ Usage: ./install.sh <oracle-vm-ip>"
    echo "Example: ./install.sh 129.213.45.123"
    exit 1
fi

echo "🚀 Starting Rathole Client Installation..."
echo "Oracle VM IP: $ORACLE_IP"
echo ""

# Detect architecture
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
    RATHOLE_ARCH="aarch64-apple-darwin"
else
    RATHOLE_ARCH="x86_64-apple-darwin"
fi

echo "📱 Detected architecture: $ARCH"

# Download Rathole
echo "⬇️  Downloading Rathole for macOS..."
cd /tmp
RATHOLE_VERSION="v0.5.0"
curl -L -o rathole.zip https://github.com/rapiz1/rathole/releases/download/${RATHOLE_VERSION}/rathole-${RATHOLE_ARCH}.zip
unzip -q rathole.zip

# Install binary
echo "📥 Installing Rathole binary..."
sudo mv rathole /usr/local/bin/
sudo chmod +x /usr/local/bin/rathole
rm rathole.zip

# Verify installation
echo "✅ Rathole installed:"
rathole --version

# Create config directory
echo "📁 Creating configuration directory..."
sudo mkdir -p /usr/local/etc/rathole

# Create config from template
echo "📝 Creating client configuration..."
cat > /tmp/client.toml <<EOF
# Rathole Client Configuration
# Auto-generated by install.sh

[client]
remote_addr = "$ORACLE_IP:2333"

# BuilderOS API Service
[client.services.builderios-api]
token = "HwH+lXVxgZu4/R9Q9oxtqbL8g2SAKRznTKBSUp51+qg="
local_addr = "127.0.0.1:8080"

# SSH Service
[client.services.ssh]
token = "TDCykmZHR1CaBKysDc+18HYE+05C9AVyCBxvDVYIb3I="
local_addr = "127.0.0.1:22"

# Transport Security
[client.transport]
type = "noise"
EOF

sudo mv /tmp/client.toml /usr/local/etc/rathole/client.toml
sudo chmod 600 /usr/local/etc/rathole/client.toml

# Create LaunchDaemon
echo "⚙️  Creating LaunchDaemon..."
sudo cp com.rathole.client.plist /Library/LaunchDaemons/
sudo chmod 644 /Library/LaunchDaemons/com.rathole.client.plist

# Test configuration
echo "🧪 Testing configuration..."
echo "Starting Rathole in test mode (5 seconds)..."
timeout 5 rathole /usr/local/etc/rathole/client.toml || true

# Load LaunchDaemon
echo "🚀 Loading LaunchDaemon..."
sudo launchctl load /Library/LaunchDaemons/com.rathole.client.plist
sudo launchctl start com.rathole.client

# Wait for startup
sleep 2

# Check status
echo ""
echo "📊 Service Status:"
if sudo launchctl list | grep -q com.rathole.client; then
    echo "✅ Rathole client is running"
else
    echo "❌ Rathole client failed to start"
    echo "Check logs: tail -f /tmp/rathole-client.log"
    exit 1
fi

echo ""
echo "✅ Installation complete!"
echo ""
echo "📝 Configuration:"
echo "  - Config file: /usr/local/etc/rathole/client.toml"
echo "  - Oracle IP: $ORACLE_IP:2333"
echo "  - Local API: 127.0.0.1:8080 → $ORACLE_IP:8080"
echo "  - Local SSH: 127.0.0.1:22 → $ORACLE_IP:2222"
echo ""
echo "📊 View logs:"
echo "  tail -f /tmp/rathole-client.log"
echo ""
echo "🔄 Control service:"
echo "  sudo launchctl stop com.rathole.client"
echo "  sudo launchctl start com.rathole.client"
echo "  sudo launchctl unload /Library/LaunchDaemons/com.rathole.client.plist"
echo ""
echo "🧪 Test tunnel:"
echo "  curl http://$ORACLE_IP:8080/health"
